### ISSUE TITLE
Failure isn't always reported back to watch

### ISSUE THREAD

**Issue by ZoneMR** [Katharine/httpebble-ios#1] opened 2013-05-20 13:13 UTC
If the phone is connected to the watch but has no internet access, HTTP requests will obviously fail, but the failed() method on the watch side doesn't seem to get invoked.

The NSURLConnection fail does get logged to the phone's console. I haven't had time to investigate exactly where the response to the watch gets lost.

**Comment by Katharine** [comment] 2013-05-20 13:45
This is caused by the app's app ID not getting sent back in the error case, which it should be.

It'd also be worth normalising the responses, probably all to 400 or something.

**Comment by Katharine** [comment] 2013-05-29 13:41
This should be fixed.

**Closed as completed by Katharine** 2013-05-29 13:41 UTC
Labels: bug
